#!/usr/bin/env bash

## launch waybar with alt config

set -euo pipefail

if [[ "${NEURONIX_SHELL_BACKEND:-classic}" != "classic" ]]; then
	exit 0
fi

CONFIG="$HOME/.config/hypr/waybar/config.jsonc"
STYLE="$HOME/.config/hypr/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
