#!/bin/bash

sketchybar --add event aerospace_workspace_change

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="MesloLGL Nerd Font Mono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default updates=when_shown                                \
                     icon.font="$FONT:Mono:15.0"                      \
                     icon.color=$WHITE                 \
                     label.font="$FONT:Mono:14.0"  \
                     label.color=$WHITE                \
                     background.corner_radius=5            \
                     background.height=26                  \
                     background.color="$TRANSPARENT"          \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \
                     icon.padding_right=4

# -- Left Side Items --
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/calendar_with_meetings.sh

# -- Right Side Items --
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/notifications.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
