{
  # User information
  username = "ext_timur.koval";
  userfullname = "Tim";
  useremail = "timkoval00@gmail.com";
  
  hostname = "A0AL0175";
  
  # Security
  # generated by `mkpasswd -m scrypt` or imported from a private file
  # initialHashedPassword = "$7$CU..../....KDvTIXqLTXpmCaoUy2yC9.$145eM358b7Q0sRXgEBvxctd5EAuEEdao57LmZjc05D.";
  # 
  # # SSH keys
  # mainSshAuthorizedKeys = [
  #   "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIKlN+Q/GxvwxDX/OAjJHaNFEznEN4Tw4E4TwqQu/eD6 ryan@idols-ai"
  #   "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFIznBmtZlMcVUL+uPFltLTNa8Y1J0aT1E36AXQV07su ryan@fern"
  # ];
  # 
  # secondaryAuthorizedKeys = [
  #   # Add any secondary keys here
  # ];
  
  # Add any other host-specific variables needed
}
